# Generated by Django 4.1.4 on 2022-12-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='amount',
            field=models.IntegerField(db_column='amount', default=1),
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='amount',
            new_name='_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='_amount',
        ),
    ]
